##Please respect the various APIs used by the app.
# The user_agent, apiKey and user_geonames information must be changed if used in a modified application!!!

#API Met.no
user_agent=wettergraph-fork-c221c22619d8 (https://github.com/macmacs/Wettergraph)
apiKey=api.met.no
#Geonames
user_geonames=af_weather
